//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SeleniumUserInterfaceParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DevToolsX.Documents.Compilers.SeleniumUserInterface.Syntax.InternalSyntax {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SeleniumUserInterfaceParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ISeleniumUserInterfaceParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUserInterfaceParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain([NotNull] SeleniumUserInterfaceParser.MainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUserInterfaceParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain([NotNull] SeleniumUserInterfaceParser.MainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUserInterfaceParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPage([NotNull] SeleniumUserInterfaceParser.PageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUserInterfaceParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPage([NotNull] SeleniumUserInterfaceParser.PageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUserInterfaceParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] SeleniumUserInterfaceParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUserInterfaceParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] SeleniumUserInterfaceParser.NameContext context);
}
} // namespace DevToolsX.Documents.Compilers.SeleniumUserInterface.Syntax.InternalSyntax

