//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MediaWikiParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DevToolsX.Documents.Compilers.MediaWiki.Syntax.InternalSyntax {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MediaWikiParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IMediaWikiParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMain([NotNull] MediaWikiParser.MainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMain([NotNull] MediaWikiParser.MainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlockOrParagraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialBlockOrParagraph([NotNull] MediaWikiParser.SpecialBlockOrParagraphContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlockOrParagraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialBlockOrParagraph([NotNull] MediaWikiParser.SpecialBlockOrParagraphContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlockWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialBlockWithComment([NotNull] MediaWikiParser.SpecialBlockWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlockWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialBlockWithComment([NotNull] MediaWikiParser.SpecialBlockWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialBlock([NotNull] MediaWikiParser.SpecialBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialBlock([NotNull] MediaWikiParser.SpecialBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeading([NotNull] MediaWikiParser.HeadingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.heading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeading([NotNull] MediaWikiParser.HeadingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingLevel([NotNull] MediaWikiParser.HeadingLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingLevel([NotNull] MediaWikiParser.HeadingLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.horizontalRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHorizontalRule([NotNull] MediaWikiParser.HorizontalRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.horizontalRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHorizontalRule([NotNull] MediaWikiParser.HorizontalRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlock([NotNull] MediaWikiParser.CodeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlock([NotNull] MediaWikiParser.CodeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.spaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpaceBlock([NotNull] MediaWikiParser.SpaceBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.spaceBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpaceBlock([NotNull] MediaWikiParser.SpaceBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiList([NotNull] MediaWikiParser.WikiListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiList([NotNull] MediaWikiParser.WikiListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.listItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListItem([NotNull] MediaWikiParser.ListItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.listItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListItem([NotNull] MediaWikiParser.ListItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.normalListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalListItem([NotNull] MediaWikiParser.NormalListItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.normalListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalListItem([NotNull] MediaWikiParser.NormalListItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitionItem([NotNull] MediaWikiParser.DefinitionItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitionItem([NotNull] MediaWikiParser.DefinitionItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiTable([NotNull] MediaWikiParser.WikiTableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiTable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiTable([NotNull] MediaWikiParser.WikiTableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCaption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableCaption([NotNull] MediaWikiParser.TableCaptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCaption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableCaption([NotNull] MediaWikiParser.TableCaptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableRows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableRows([NotNull] MediaWikiParser.TableRowsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableRows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableRows([NotNull] MediaWikiParser.TableRowsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableFirstRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableFirstRow([NotNull] MediaWikiParser.TableFirstRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableFirstRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableFirstRow([NotNull] MediaWikiParser.TableFirstRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableNonFirstRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableNonFirstRow([NotNull] MediaWikiParser.TableNonFirstRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableNonFirstRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableNonFirstRow([NotNull] MediaWikiParser.TableNonFirstRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableRowStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableRowStart([NotNull] MediaWikiParser.TableRowStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableRowStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableRowStart([NotNull] MediaWikiParser.TableRowStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableRow([NotNull] MediaWikiParser.TableRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableRow([NotNull] MediaWikiParser.TableRowContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableColumn([NotNull] MediaWikiParser.TableColumnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableColumn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableColumn([NotNull] MediaWikiParser.TableColumnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableSingleHeaderCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableSingleHeaderCell([NotNull] MediaWikiParser.TableSingleHeaderCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableSingleHeaderCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableSingleHeaderCell([NotNull] MediaWikiParser.TableSingleHeaderCellContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableHeaderCells"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableHeaderCells([NotNull] MediaWikiParser.TableHeaderCellsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableHeaderCells"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableHeaderCells([NotNull] MediaWikiParser.TableHeaderCellsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableSingleCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableSingleCell([NotNull] MediaWikiParser.TableSingleCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableSingleCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableSingleCell([NotNull] MediaWikiParser.TableSingleCellContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCells"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableCells([NotNull] MediaWikiParser.TableCellsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCells"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableCells([NotNull] MediaWikiParser.TableCellsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableCell([NotNull] MediaWikiParser.TableCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableCell([NotNull] MediaWikiParser.TableCellContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellAttributes([NotNull] MediaWikiParser.CellAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellAttributes([NotNull] MediaWikiParser.CellAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.paragraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParagraph([NotNull] MediaWikiParser.ParagraphContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.paragraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParagraph([NotNull] MediaWikiParser.ParagraphContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>textLineInlineElementsWithComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextLineInlineElementsWithComment([NotNull] MediaWikiParser.TextLineInlineElementsWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>textLineInlineElementsWithComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextLineInlineElementsWithComment([NotNull] MediaWikiParser.TextLineInlineElementsWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>textLineComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextLineComment([NotNull] MediaWikiParser.TextLineCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>textLineComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextLineComment([NotNull] MediaWikiParser.TextLineCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.textElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTextElements([NotNull] MediaWikiParser.TextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.textElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTextElements([NotNull] MediaWikiParser.TextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineText([NotNull] MediaWikiParser.InlineTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineText([NotNull] MediaWikiParser.InlineTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineTextElementWithComment([NotNull] MediaWikiParser.InlineTextElementWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineTextElementWithComment([NotNull] MediaWikiParser.InlineTextElementWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineTextElement([NotNull] MediaWikiParser.InlineTextElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineTextElement([NotNull] MediaWikiParser.InlineTextElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineTextElements([NotNull] MediaWikiParser.InlineTextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineTextElements([NotNull] MediaWikiParser.InlineTextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitionText([NotNull] MediaWikiParser.DefinitionTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitionText([NotNull] MediaWikiParser.DefinitionTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitionTextElementWithComment([NotNull] MediaWikiParser.DefinitionTextElementWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitionTextElementWithComment([NotNull] MediaWikiParser.DefinitionTextElementWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitionTextElement([NotNull] MediaWikiParser.DefinitionTextElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitionTextElement([NotNull] MediaWikiParser.DefinitionTextElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitionTextElements([NotNull] MediaWikiParser.DefinitionTextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitionTextElements([NotNull] MediaWikiParser.DefinitionTextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingText([NotNull] MediaWikiParser.HeadingTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingText([NotNull] MediaWikiParser.HeadingTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingTextWithComment([NotNull] MediaWikiParser.HeadingTextWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingTextWithComment([NotNull] MediaWikiParser.HeadingTextWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingTextElement([NotNull] MediaWikiParser.HeadingTextElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingTextElement([NotNull] MediaWikiParser.HeadingTextElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeadingTextElements([NotNull] MediaWikiParser.HeadingTextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeadingTextElements([NotNull] MediaWikiParser.HeadingTextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellText([NotNull] MediaWikiParser.CellTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellText([NotNull] MediaWikiParser.CellTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellTextElementWithComment([NotNull] MediaWikiParser.CellTextElementWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElementWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellTextElementWithComment([NotNull] MediaWikiParser.CellTextElementWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellTextElement([NotNull] MediaWikiParser.CellTextElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellTextElement([NotNull] MediaWikiParser.CellTextElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellTextElements([NotNull] MediaWikiParser.CellTextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellTextElements([NotNull] MediaWikiParser.CellTextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkText([NotNull] MediaWikiParser.LinkTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkText([NotNull] MediaWikiParser.LinkTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkTextWithComment([NotNull] MediaWikiParser.LinkTextWithCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextWithComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkTextWithComment([NotNull] MediaWikiParser.LinkTextWithCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkTextElement([NotNull] MediaWikiParser.LinkTextElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkTextElement([NotNull] MediaWikiParser.LinkTextElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkTextElements([NotNull] MediaWikiParser.LinkTextElementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkTextElements([NotNull] MediaWikiParser.LinkTextElementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiFormat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiFormat([NotNull] MediaWikiParser.WikiFormatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiFormat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiFormat([NotNull] MediaWikiParser.WikiFormatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiLink([NotNull] MediaWikiParser.WikiLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiLink([NotNull] MediaWikiParser.WikiLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiInternalLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiInternalLink([NotNull] MediaWikiParser.WikiInternalLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiInternalLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiInternalLink([NotNull] MediaWikiParser.WikiInternalLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiExternalLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiExternalLink([NotNull] MediaWikiParser.WikiExternalLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiExternalLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiExternalLink([NotNull] MediaWikiParser.WikiExternalLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiTemplate([NotNull] MediaWikiParser.WikiTemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiTemplate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiTemplate([NotNull] MediaWikiParser.WikiTemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiTemplateParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWikiTemplateParam([NotNull] MediaWikiParser.WikiTemplateParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiTemplateParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWikiTemplateParam([NotNull] MediaWikiParser.WikiTemplateParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.noWiki"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoWiki([NotNull] MediaWikiParser.NoWikiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.noWiki"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoWiki([NotNull] MediaWikiParser.NoWikiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.barOrBarBar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBarOrBarBar([NotNull] MediaWikiParser.BarOrBarBarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.barOrBarBar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBarOrBarBar([NotNull] MediaWikiParser.BarOrBarBarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkTextPart([NotNull] MediaWikiParser.LinkTextPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkTextPart([NotNull] MediaWikiParser.LinkTextPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlReference([NotNull] MediaWikiParser.HtmlReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlReference([NotNull] MediaWikiParser.HtmlReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlCommentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlCommentList([NotNull] MediaWikiParser.HtmlCommentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlCommentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlCommentList([NotNull] MediaWikiParser.HtmlCommentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlComment([NotNull] MediaWikiParser.HtmlCommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlComment([NotNull] MediaWikiParser.HtmlCommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlStyle([NotNull] MediaWikiParser.HtmlStyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlStyle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlStyle([NotNull] MediaWikiParser.HtmlStyleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlScript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlScript([NotNull] MediaWikiParser.HtmlScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlScript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlScript([NotNull] MediaWikiParser.HtmlScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTag([NotNull] MediaWikiParser.HtmlTagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTag([NotNull] MediaWikiParser.HtmlTagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTagOpen([NotNull] MediaWikiParser.HtmlTagOpenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagOpen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTagOpen([NotNull] MediaWikiParser.HtmlTagOpenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTagClose([NotNull] MediaWikiParser.HtmlTagCloseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagClose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTagClose([NotNull] MediaWikiParser.HtmlTagCloseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTagEmpty([NotNull] MediaWikiParser.HtmlTagEmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagEmpty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTagEmpty([NotNull] MediaWikiParser.HtmlTagEmptyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>htmlAttributeWithValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeWithValue([NotNull] MediaWikiParser.HtmlAttributeWithValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>htmlAttributeWithValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeWithValue([NotNull] MediaWikiParser.HtmlAttributeWithValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>htmlAttributeWithNoValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeWithNoValue([NotNull] MediaWikiParser.HtmlAttributeWithNoValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>htmlAttributeWithNoValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeWithNoValue([NotNull] MediaWikiParser.HtmlAttributeWithNoValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlAttributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeName([NotNull] MediaWikiParser.HtmlAttributeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlAttributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeName([NotNull] MediaWikiParser.HtmlAttributeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlAttributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlAttributeValue([NotNull] MediaWikiParser.HtmlAttributeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlAttributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlAttributeValue([NotNull] MediaWikiParser.HtmlAttributeValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHtmlTagName([NotNull] MediaWikiParser.HtmlTagNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHtmlTagName([NotNull] MediaWikiParser.HtmlTagNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.whitespaceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhitespaceList([NotNull] MediaWikiParser.WhitespaceListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.whitespaceList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhitespaceList([NotNull] MediaWikiParser.WhitespaceListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.whitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhitespace([NotNull] MediaWikiParser.WhitespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.whitespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhitespace([NotNull] MediaWikiParser.WhitespaceContext context);
}
} // namespace DevToolsX.Documents.Compilers.MediaWiki.Syntax.InternalSyntax

