//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MediaWikiParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DevToolsX.Documents.Compilers.MediaWiki.Syntax.InternalSyntax {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMediaWikiParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class MediaWikiParserBaseListener : IMediaWikiParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] MediaWikiParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] MediaWikiParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlockOrParagraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialBlockOrParagraph([NotNull] MediaWikiParser.SpecialBlockOrParagraphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlockOrParagraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialBlockOrParagraph([NotNull] MediaWikiParser.SpecialBlockOrParagraphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlockWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialBlockWithComment([NotNull] MediaWikiParser.SpecialBlockWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlockWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialBlockWithComment([NotNull] MediaWikiParser.SpecialBlockWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.specialBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialBlock([NotNull] MediaWikiParser.SpecialBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.specialBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialBlock([NotNull] MediaWikiParser.SpecialBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeading([NotNull] MediaWikiParser.HeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.heading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeading([NotNull] MediaWikiParser.HeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingLevel([NotNull] MediaWikiParser.HeadingLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingLevel([NotNull] MediaWikiParser.HeadingLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.horizontalRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHorizontalRule([NotNull] MediaWikiParser.HorizontalRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.horizontalRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHorizontalRule([NotNull] MediaWikiParser.HorizontalRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.spaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpaceBlock([NotNull] MediaWikiParser.SpaceBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.spaceBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpaceBlock([NotNull] MediaWikiParser.SpaceBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.listItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListItem([NotNull] MediaWikiParser.ListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.listItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListItem([NotNull] MediaWikiParser.ListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.normalListItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormalListItem([NotNull] MediaWikiParser.NormalListItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.normalListItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormalListItem([NotNull] MediaWikiParser.NormalListItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitionItem([NotNull] MediaWikiParser.DefinitionItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitionItem([NotNull] MediaWikiParser.DefinitionItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable([NotNull] MediaWikiParser.TableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.table"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable([NotNull] MediaWikiParser.TableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCaption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableCaption([NotNull] MediaWikiParser.TableCaptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCaption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableCaption([NotNull] MediaWikiParser.TableCaptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableRows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableRows([NotNull] MediaWikiParser.TableRowsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableRows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableRows([NotNull] MediaWikiParser.TableRowsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableFirstRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableFirstRow([NotNull] MediaWikiParser.TableFirstRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableFirstRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableFirstRow([NotNull] MediaWikiParser.TableFirstRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableRow([NotNull] MediaWikiParser.TableRowContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableRow"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableRow([NotNull] MediaWikiParser.TableRowContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableColumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableColumn([NotNull] MediaWikiParser.TableColumnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableColumn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableColumn([NotNull] MediaWikiParser.TableColumnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableSingleHeaderCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableSingleHeaderCell([NotNull] MediaWikiParser.TableSingleHeaderCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableSingleHeaderCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableSingleHeaderCell([NotNull] MediaWikiParser.TableSingleHeaderCellContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableHeaderCells"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableHeaderCells([NotNull] MediaWikiParser.TableHeaderCellsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableHeaderCells"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableHeaderCells([NotNull] MediaWikiParser.TableHeaderCellsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableSingleCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableSingleCell([NotNull] MediaWikiParser.TableSingleCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableSingleCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableSingleCell([NotNull] MediaWikiParser.TableSingleCellContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCells"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableCells([NotNull] MediaWikiParser.TableCellsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCells"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableCells([NotNull] MediaWikiParser.TableCellsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.tableCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableCell([NotNull] MediaWikiParser.TableCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.tableCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableCell([NotNull] MediaWikiParser.TableCellContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextOpt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellTextOpt([NotNull] MediaWikiParser.CellTextOptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextOpt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellTextOpt([NotNull] MediaWikiParser.CellTextOptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.paragraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParagraph([NotNull] MediaWikiParser.ParagraphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.paragraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParagraph([NotNull] MediaWikiParser.ParagraphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>textLineInlineElementsWithComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLineInlineElementsWithComment([NotNull] MediaWikiParser.TextLineInlineElementsWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>textLineInlineElementsWithComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLineInlineElementsWithComment([NotNull] MediaWikiParser.TextLineInlineElementsWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>textLineComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextLineComment([NotNull] MediaWikiParser.TextLineCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>textLineComment</c>
	/// labeled alternative in <see cref="MediaWikiParser.textLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextLineComment([NotNull] MediaWikiParser.TextLineCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.textElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextElements([NotNull] MediaWikiParser.TextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.textElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextElements([NotNull] MediaWikiParser.TextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineText([NotNull] MediaWikiParser.InlineTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineText([NotNull] MediaWikiParser.InlineTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineTextElementWithComment([NotNull] MediaWikiParser.InlineTextElementWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineTextElementWithComment([NotNull] MediaWikiParser.InlineTextElementWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineTextElement([NotNull] MediaWikiParser.InlineTextElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineTextElement([NotNull] MediaWikiParser.InlineTextElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.inlineTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineTextElements([NotNull] MediaWikiParser.InlineTextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.inlineTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineTextElements([NotNull] MediaWikiParser.InlineTextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitionText([NotNull] MediaWikiParser.DefinitionTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitionText([NotNull] MediaWikiParser.DefinitionTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitionTextElementWithComment([NotNull] MediaWikiParser.DefinitionTextElementWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitionTextElementWithComment([NotNull] MediaWikiParser.DefinitionTextElementWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitionTextElement([NotNull] MediaWikiParser.DefinitionTextElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitionTextElement([NotNull] MediaWikiParser.DefinitionTextElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.definitionTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinitionTextElements([NotNull] MediaWikiParser.DefinitionTextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.definitionTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinitionTextElements([NotNull] MediaWikiParser.DefinitionTextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingText([NotNull] MediaWikiParser.HeadingTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingText([NotNull] MediaWikiParser.HeadingTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingTextWithComment([NotNull] MediaWikiParser.HeadingTextWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingTextWithComment([NotNull] MediaWikiParser.HeadingTextWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingTextElement([NotNull] MediaWikiParser.HeadingTextElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingTextElement([NotNull] MediaWikiParser.HeadingTextElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.headingTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeadingTextElements([NotNull] MediaWikiParser.HeadingTextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.headingTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeadingTextElements([NotNull] MediaWikiParser.HeadingTextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellText([NotNull] MediaWikiParser.CellTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellText([NotNull] MediaWikiParser.CellTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellTextElementWithComment([NotNull] MediaWikiParser.CellTextElementWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElementWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellTextElementWithComment([NotNull] MediaWikiParser.CellTextElementWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellTextElement([NotNull] MediaWikiParser.CellTextElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellTextElement([NotNull] MediaWikiParser.CellTextElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.cellTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellTextElements([NotNull] MediaWikiParser.CellTextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.cellTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellTextElements([NotNull] MediaWikiParser.CellTextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkText([NotNull] MediaWikiParser.LinkTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkText([NotNull] MediaWikiParser.LinkTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkTextWithComment([NotNull] MediaWikiParser.LinkTextWithCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextWithComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkTextWithComment([NotNull] MediaWikiParser.LinkTextWithCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkTextElement([NotNull] MediaWikiParser.LinkTextElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkTextElement([NotNull] MediaWikiParser.LinkTextElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkTextElements([NotNull] MediaWikiParser.LinkTextElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkTextElements([NotNull] MediaWikiParser.LinkTextElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiFormat([NotNull] MediaWikiParser.WikiFormatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiFormat([NotNull] MediaWikiParser.WikiFormatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiLink([NotNull] MediaWikiParser.WikiLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiLink([NotNull] MediaWikiParser.WikiLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiInternalLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiInternalLink([NotNull] MediaWikiParser.WikiInternalLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiInternalLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiInternalLink([NotNull] MediaWikiParser.WikiInternalLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiExternalLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiExternalLink([NotNull] MediaWikiParser.WikiExternalLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiExternalLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiExternalLink([NotNull] MediaWikiParser.WikiExternalLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiTemplate([NotNull] MediaWikiParser.WikiTemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiTemplate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiTemplate([NotNull] MediaWikiParser.WikiTemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.wikiTemplateParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWikiTemplateParam([NotNull] MediaWikiParser.WikiTemplateParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.wikiTemplateParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWikiTemplateParam([NotNull] MediaWikiParser.WikiTemplateParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.noWiki"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoWiki([NotNull] MediaWikiParser.NoWikiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.noWiki"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoWiki([NotNull] MediaWikiParser.NoWikiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.barOrBarBar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBarOrBarBar([NotNull] MediaWikiParser.BarOrBarBarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.barOrBarBar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBarOrBarBar([NotNull] MediaWikiParser.BarOrBarBarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.linkTextPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinkTextPart([NotNull] MediaWikiParser.LinkTextPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.linkTextPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinkTextPart([NotNull] MediaWikiParser.LinkTextPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlReference([NotNull] MediaWikiParser.HtmlReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlReference([NotNull] MediaWikiParser.HtmlReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlCommentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlCommentList([NotNull] MediaWikiParser.HtmlCommentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlCommentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlCommentList([NotNull] MediaWikiParser.HtmlCommentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlComment([NotNull] MediaWikiParser.HtmlCommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlComment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlComment([NotNull] MediaWikiParser.HtmlCommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlStyle([NotNull] MediaWikiParser.HtmlStyleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlStyle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlStyle([NotNull] MediaWikiParser.HtmlStyleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlScript([NotNull] MediaWikiParser.HtmlScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlScript([NotNull] MediaWikiParser.HtmlScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTag([NotNull] MediaWikiParser.HtmlTagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTag([NotNull] MediaWikiParser.HtmlTagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagOpen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagOpen([NotNull] MediaWikiParser.HtmlTagOpenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagOpen"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagOpen([NotNull] MediaWikiParser.HtmlTagOpenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagClose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagClose([NotNull] MediaWikiParser.HtmlTagCloseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagClose"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagClose([NotNull] MediaWikiParser.HtmlTagCloseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagEmpty([NotNull] MediaWikiParser.HtmlTagEmptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagEmpty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagEmpty([NotNull] MediaWikiParser.HtmlTagEmptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>htmlAttributeWithValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeWithValue([NotNull] MediaWikiParser.HtmlAttributeWithValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>htmlAttributeWithValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeWithValue([NotNull] MediaWikiParser.HtmlAttributeWithValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>htmlAttributeWithNoValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeWithNoValue([NotNull] MediaWikiParser.HtmlAttributeWithNoValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>htmlAttributeWithNoValue</c>
	/// labeled alternative in <see cref="MediaWikiParser.htmlAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeWithNoValue([NotNull] MediaWikiParser.HtmlAttributeWithNoValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlAttributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeName([NotNull] MediaWikiParser.HtmlAttributeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlAttributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeName([NotNull] MediaWikiParser.HtmlAttributeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlAttributeValue([NotNull] MediaWikiParser.HtmlAttributeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlAttributeValue([NotNull] MediaWikiParser.HtmlAttributeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.htmlTagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagName([NotNull] MediaWikiParser.HtmlTagNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.htmlTagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagName([NotNull] MediaWikiParser.HtmlTagNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.whitespaceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhitespaceList([NotNull] MediaWikiParser.WhitespaceListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.whitespaceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhitespaceList([NotNull] MediaWikiParser.WhitespaceListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MediaWikiParser.whitespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhitespace([NotNull] MediaWikiParser.WhitespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MediaWikiParser.whitespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhitespace([NotNull] MediaWikiParser.WhitespaceContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace DevToolsX.Documents.Compilers.MediaWiki.Syntax.InternalSyntax
