//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SeleniumUIParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DevToolsX.Documents.Compilers.SeleniumUI.Syntax.InternalSyntax {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISeleniumUIParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class SeleniumUIParserBaseListener : ISeleniumUIParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] SeleniumUIParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] SeleniumUIParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace([NotNull] SeleniumUIParser.NamespaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.namespace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace([NotNull] SeleniumUIParser.NamespaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.namespaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceBody([NotNull] SeleniumUIParser.NamespaceBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.namespaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceBody([NotNull] SeleniumUIParser.NamespaceBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] SeleniumUIParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] SeleniumUIParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] SeleniumUIParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] SeleniumUIParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpecifier([NotNull] SeleniumUIParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpecifier([NotNull] SeleniumUIParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] SeleniumUIParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] SeleniumUIParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.elementOrPage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementOrPage([NotNull] SeleniumUIParser.ElementOrPageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.elementOrPage"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementOrPage([NotNull] SeleniumUIParser.ElementOrPageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.baseElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseElement([NotNull] SeleniumUIParser.BaseElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.baseElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseElement([NotNull] SeleniumUIParser.BaseElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.elementBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementBody([NotNull] SeleniumUIParser.ElementBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.elementBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementBody([NotNull] SeleniumUIParser.ElementBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.emptyElementBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyElementBody([NotNull] SeleniumUIParser.EmptyElementBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.emptyElementBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyElementBody([NotNull] SeleniumUIParser.EmptyElementBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.childElementsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChildElementsBody([NotNull] SeleniumUIParser.ChildElementsBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.childElementsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChildElementsBody([NotNull] SeleniumUIParser.ChildElementsBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.childElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChildElement([NotNull] SeleniumUIParser.ChildElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.childElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChildElement([NotNull] SeleniumUIParser.ChildElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.elementTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementTypeSpecifier([NotNull] SeleniumUIParser.ElementTypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.elementTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementTypeSpecifier([NotNull] SeleniumUIParser.ElementTypeSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.htmlTagLocatorSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagLocatorSpecifier([NotNull] SeleniumUIParser.HtmlTagLocatorSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.htmlTagLocatorSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagLocatorSpecifier([NotNull] SeleniumUIParser.HtmlTagLocatorSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.htmlTagSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHtmlTagSpecifier([NotNull] SeleniumUIParser.HtmlTagSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.htmlTagSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHtmlTagSpecifier([NotNull] SeleniumUIParser.HtmlTagSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.locatorSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocatorSpecifier([NotNull] SeleniumUIParser.LocatorSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.locatorSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocatorSpecifier([NotNull] SeleniumUIParser.LocatorSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] SeleniumUIParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] SeleniumUIParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] SeleniumUIParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] SeleniumUIParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifier([NotNull] SeleniumUIParser.QualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifier([NotNull] SeleniumUIParser.QualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] SeleniumUIParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] SeleniumUIParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SeleniumUIParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] SeleniumUIParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SeleniumUIParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] SeleniumUIParser.StringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace DevToolsX.Documents.Compilers.SeleniumUI.Syntax.InternalSyntax

